/**
 * Shared type definitions used by both frontend and backend
 */

import type { MacOpenMode, MacSizing } from './mac-sessions.js';

/**
 * HTTP methods enum
 */
export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
}

/**
 * Types of server events delivered over WebSocket v3 `EVENT` frames.
 * Matches the Swift ServerEventType enum for type safety across platforms.
 */
export enum ServerEventType {
  SessionStart = 'session-start',
  SessionExit = 'session-exit',
  CommandFinished = 'command-finished',
  CommandError = 'command-error',
  Bell = 'bell',
  Connected = 'connected',
  TestNotification = 'test-notification',
}

/**
 * Server event delivered over WebSocket v3 `EVENT` frames.
 * Matches the Swift ServerEvent struct for cross-platform compatibility.
 */
export interface ServerEvent {
  type: ServerEventType;
  sessionId?: string;
  sessionName?: string;
  command?: string;
  exitCode?: number;
  duration?: number;
  processInfo?: string;
  message?: string;
  timestamp: string; // ISO 8601 format
  // Test notification specific fields
  title?: string;
  body?: string;
}

/**
 * Session status enum
 */
export type SessionStatus = 'starting' | 'running' | 'exited';

/**
 * A tmux session outside VibeTunnel that a session is attached to: its PTY runs a tmux client
 * of that session, opened from "On this computer". Disconnecting detaches that client; the tmux
 * session keeps running.
 */
export interface SessionMultiplexer {
  type: 'tmux';
  socketPath: string;
  /** The tmux server process, and its start time in epoch seconds (a restarted one differs). */
  serverPid: number;
  serverStartedAt: number;
  /** tmux's id of the session ("$3"), and its name. */
  sessionId: string;
  sessionName: string;
  mode: MacOpenMode;
  sizing: MacSizing;
  source: 'mac-sessions' | 'multiplexer-modal';
}

/**
 * Core session information stored in session.json
 * Minimal, clean data persisted to disk
 */
export interface SessionInfo {
  id: string;
  name: string;
  command: string[];
  workingDir: string;
  status: SessionStatus;
  exitCode?: number;
  startedAt: string;
  pid?: number;
  initialCols?: number;
  initialRows?: number;
  /**
   * Byte offset of the last clear event in the session stdout file.
   * Used to quickly seek to the most recent content when replaying casts.
   */
  lastClearOffset?: number;
  version?: string; // VibeTunnel version that created this session
  gitRepoPath?: string; // Repository root path
  gitBranch?: string; // Current branch name
  gitAheadCount?: number; // Commits ahead of upstream
  gitBehindCount?: number; // Commits behind upstream
  gitHasChanges?: boolean; // Has uncommitted changes
  gitIsWorktree?: boolean; // Is a worktree (not main repo)
  gitMainRepoPath?: string; // Main repository path (same as gitRepoPath if not worktree)
  // Git status details (not persisted to disk, fetched dynamically)
  gitModifiedCount?: number; // Number of modified files
  gitUntrackedCount?: number; // Number of untracked files
  gitStagedCount?: number; // Number of staged files
  gitAddedCount?: number; // Number of added files
  gitDeletedCount?: number; // Number of deleted files
  gitInsertionCount?: number; // Number of inserted lines
  gitDeletionCount?: number; // Number of deleted lines
  /**
   * Whether this session was spawned from within VibeTunnel itself.
   * Used to distinguish between direct terminal sessions and nested VibeTunnel sessions.
   * Sessions with attachedViaVT=true are spawned from within an existing VibeTunnel session.
   */
  attachedViaVT?: boolean;
  /** Claude Code conversation last seen running in this session (agent chat on). */
  claudeSessionId?: string;
  /** Claude's conversation title, kept after the session exits. */
  claudeTitle?: string;
  /** Attached to a tmux session outside VibeTunnel. */
  multiplexer?: SessionMultiplexer;
}

/**
 * Session as returned by API endpoints
 * Includes everything from SessionInfo plus additional runtime/computed fields
 */
export interface Session extends SessionInfo {
  lastModified: string;
  active?: boolean;

  activityStatus?: {
    isActive: boolean;
    lastActivityAt?: string;
  };

  /** Exited Claude session whose conversation can be resumed (`claude --resume`; agent chat). */
  claudeResumable?: boolean;

  // Source information (for HQ mode)
  source?: 'local' | 'remote';
  remoteId?: string;
  remoteName?: string;
  remoteUrl?: string;

  /** Claude Code running in this session (only while agent chat is on). */
  claudeStatus?: {
    status: string;
    waitingFor?: string;
    /** Conversation title generated by Claude Code. */
    title?: string;
    /** Last user or assistant message, one line. */
    preview?: { role: 'user' | 'assistant'; text: string };
    /**
     * While waiting: the menu on screen (permission prompts), answered through /answer, and what
     * it is about ("Bash command", the command), which tells apart prompts with the same options.
     */
    choices?: { question: string; options: string[]; detail?: string[]; key?: string };
    /** When the current status began (epoch ms). */
    since?: number;
    /**
     * While busy: what Claude is doing right now. `kind` "tool" names the tool still running
     * and its short subject (command, file name, pattern, host…); `since` is when that began.
     */
    activity?: {
      kind: 'thinking' | 'writing' | 'tool';
      tool?: string;
      target?: string;
      since?: number;
    };
    /**
     * Busy only because background agents or tasks still run: Claude's reply is over and it
     * waits for the user (Claude Code says "busy" until they all end).
     */
    waitingForBackground?: boolean;
  };

  /**
   * Running non-Claude session: the last line of output on screen, without the shell prompt
   * (plain text, at most 120 characters). Only when the list asks for it (`?lastLine=1`).
   */
  lastLine?: string;

  /** Running OpenAI Codex session: its first prompt, as the conversation title (agent chat). */
  codexTitle?: string;

  /** OpenAI Codex runs in this session (its command, or typed inside its shell; agent chat). */
  codexActive?: boolean;

  /** Running Gemini CLI session: its first prompt, as the conversation title (agent chat). */
  geminiTitle?: string;

  /** Gemini CLI runs in this session (its command, or typed inside its shell; agent chat). */
  geminiActive?: boolean;
}

/**
 * Terminal title management modes
 */
export enum TitleMode {
  NONE = 'none', // No title management
  FILTER = 'filter', // Block all title changes from apps
  STATIC = 'static', // Static title: path — command — session
}

/**
 * Session creation options
 */
export interface SessionCreateOptions {
  sessionId?: string;
  name?: string;
  workingDir?: string;
  cols?: number;
  rows?: number;
  titleMode?: TitleMode;
  gitRepoPath?: string;
  gitBranch?: string;
  gitAheadCount?: number;
  gitBehindCount?: number;
  gitHasChanges?: boolean;
  gitIsWorktree?: boolean;
  gitMainRepoPath?: string;
  /** Attach to a tmux session outside VibeTunnel. */
  multiplexer?: SessionMultiplexer;
}

/**
 * Session input (keyboard/special keys)
 */
export interface SessionInput {
  text?: string;
  key?: SpecialKey;
}

/**
 * Special keys that can be sent to sessions
 */
export type SpecialKey =
  | 'arrow_up'
  | 'arrow_down'
  | 'arrow_left'
  | 'arrow_right'
  | 'escape'
  | 'enter'
  | 'ctrl_enter'
  | 'shift_enter'
  | 'backspace'
  | 'tab'
  | 'shift_tab'
  | 'page_up'
  | 'page_down'
  | 'home'
  | 'end'
  | 'delete'
  | 'f1'
  | 'f2'
  | 'f3'
  | 'f4'
  | 'f5'
  | 'f6'
  | 'f7'
  | 'f8'
  | 'f9'
  | 'f10'
  | 'f11'
  | 'f12';

/**
 * Push notification subscription
 */
export interface PushSubscription {
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
}

/**
 * Stored push subscription with metadata
 */
export interface StoredPushSubscription extends PushSubscription {
  id: string;
  deviceId: string;
  userAgent?: string;
  createdAt: string;
  lastUsed: string;
}

/**
 * Push notification preferences
 */
export interface PushNotificationPreferences {
  enabled: boolean;
  sessionExit: boolean;
  sessionStart: boolean;
  sessionError: boolean;
  commandNotifications: boolean;
  systemAlerts: boolean;
  soundEnabled: boolean;
  vibrationEnabled: boolean;
}

/**
 * Push notification types
 */
export type PushNotificationType =
  | 'session_exit'
  | 'session_start'
  | 'session_error'
  | 'system_alert'
  | 'test';

/**
 * Push notification data
 */
export interface PushNotificationData {
  type: PushNotificationType;
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: Record<string, unknown>;
  actions?: Array<{
    action: string;
    title: string;
    icon?: string;
  }>;
  requireInteraction?: boolean;
  silent?: boolean;
}

/**
 * Push notification history entry
 */
export interface PushNotificationHistoryEntry {
  id: string;
  timestamp: string;
  type: PushNotificationType;
  title: string;
  body: string;
  success: boolean;
  error?: string;
  deviceId?: string;
}

/**
 * Device registration for push notifications
 */
export interface PushDeviceRegistration {
  deviceId: string;
  subscription: PushSubscription;
  userAgent?: string;
}

/**
 * Server status information
 */
export interface ServerStatus {
  macAppConnected: boolean;
  isHQMode: boolean;
  version: string;
}
